# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramlite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data',
            field=models.TextField(max_length=3000),
        ),
    ]
