# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramlite', '0002_auto_20160214_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
