# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gramlite', '0003_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='data',
        ),
    ]
