# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gramlite', '0004_remove_user_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.CharField(max_length=3000)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gramlite.User')),
            ],
        ),
    ]
