# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gramlite', '0005_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gramlite.User'),
        ),
    ]
